INFO:__main__:Starting bot
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/twopercent/PycharmProjects/pythonProject/Commercial/HH_bot/venv/lib/python3.10/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
WARNING:aiogram.dispatcher.dispatcher:Polling is stopped.
ERROR:__main__:Bot stopped!
INFO:aiogram.dispatcher.dispatcher:Stop polling...
INFO:__main__:Starting bot
INFO:aiogram.dispatcher.dispatcher:Start polling.
WARNING:aiogram.dispatcher.dispatcher:Polling is stopped.
ERROR:__main__:Bot stopped!
INFO:aiogram.dispatcher.dispatcher:Stop polling...
